### ISSUE TITLE
GitHub not linked on npm package page

### ISSUE THREAD

**Issue by TranquilMarmot** [ParamagicDev/shadow-dom-testing-library#9]
The GitHub repo for this package is not listed on its npm page:

https://www.npmjs.com/package/shadow-dom-testing-library

I had to dig a bit to find this 😄

**Comment by ParamagicDev** [comment]
Doh! Thanks! I'll update it!

**Comment by ParamagicDev** [comment]
Fixed in v1.1.6.

https://github.com/ParamagicDev/shadow-dom-testing-library/commit/ae36ba81be8e762a514632d90705463701d316c6
